modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/Tinkers-Reforged/issues"

[[mods]]
modId = "tinkers_reforged"
version = "2.20.0.7"
displayName = "Tinkers Reforged"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged"
#logoFile="tinkers_reforged_logo.png"
credits = "Materialis and The Tinkers Devs for their help"
authors = "Mrthomas20121"
description = '''
Add new materials to Tinkers Construct
'''

[[dependencies.tinkers_reforged]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_reforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_reforged]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.12.0.220,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_reforged]]
    modId="jei"
    mandatory=true
    versionRange="[15.56.0.204,)"
    ordering="NONE"
    side="BOTH"